version: 2.1
orbs:
  node: circleci/node@4.7.0
jobs:
  build:
    docker:
      - image: cimg/node:20.10.1
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Run TypeScript compiler
          command: npm run tsc
      - run:
          name: Build
          command: npm run build
      - run:
          name: Test
          command: npm run test
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
