version: 2.1
orbs:
  node: circleci/node@4.7.0
jobs:
  build:
    docker:
      - image: cypress/browsers:node14.17.0-chrome91-ff89
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Run lint
          command: npm run lint
      - run:
          name: Run TypeScript compiler
          command: npm run tsc
      - run:
          name: Build
          command: npm run build
      - run:
          name: Debug Information
          command: |
            echo "Node.js version: $(node -v)"
            echo "npm version: $(npm -v)"
            echo "Cypress version: $(npx cypress -v)"
            # Add more debugging commands as needed
      - run:
          name: Install Cypress dependencies
          command: npm install --save-dev cypress
      - run:
          name: Cypress Headless
          command: npm run cypress
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
