version: 2.1
orbs:
  node: circleci/node@4.7.0
jobs:
  build:
    docker:
      - image: cypress/browsers:node16.15.1.-chrome91-ff89
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Run lint
          command: npm run lint
      - run:
          name: Run TypeScript compiler
          command: npm run tsc
      - run:
          name: Build
          command: npm run build
      - run:
          name: Install Cypress dependencies
          command: npm install --save-dev cypress
      - run:
          name: Cypress Headless
          command: npm run cypress
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
