version: 2.1

jobs:
  cypress-run:
    docker:
      - image: cypress/browsers:node14.17.0-chrome91-ff89
    steps:
      - checkout
      - run:
          name: Clear npm cache
          command: npm cache clean --force
      - restore_cache:
          keys:
            - cypress-{{ .Branch }}-{{ checksum "package-lock.json" }}
      - run:
          name: Install dependencies
          command: npm ci
      - save_cache:
          key: cypress-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      - run:
          name: Run lint
          command: npm run lint
      - run:
          name: Run TypeScript compiler
          command: npm run tsc
      - run:
          name: Build
          command: npm run build
      - run:
          name: Cypress Headless
          command: npm run cypress

workflows:
  version: 2
  build_and_test:
    jobs:
      - cypress-run
